# config.yaml

checkInterval: 60

lark:
  webhookUrl: "你的飞书机器人 WEBHOOK_URL"

# systemd 状态监控 (检查服务是否 active)
systemd:
  services:
    - "nginx.service"
    - "sshd.service"

# 新增部分：journald 日志监控 (检查服务日志中的关键字)
journal:
  - serviceName: "nginx.service"
    keywords:
      - "error"
      - "failed"
      - "denied"
  - serviceName: "sshd.service"
    keywords:
      - "Failed password"
      - "Invalid user"